name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project with environment variables
        env:
          REACT_APP_EMAILJS_USER_ID: ${{ secrets.REACT_APP_EMAILJS_USER_ID }}
          REACT_APP_EMAILJS_SERVICE_ID: ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }}
          REACT_APP_EMAILJS_TEMPLATE_ID_PT: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID_PT }}
          REACT_APP_EMAILJS_TEMPLATE_ID_ENG: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID_ENG }}
          REACT_APP_RECAPTCHA_KEY: ${{ secrets.REACT_APP_RECAPTCHA_KEY }}
          REACT_APP_FONTAWESOME_KIT_KEY: ${{ secrets.REACT_APP_FONTAWESOME_KIT_KEY }}
        run: npm run build

      - name: Set Git identity for deployment
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          npx gh-pages -d build -b gh-pages \
            -u "GitHub Actions <actions@github.com>" \
            -r "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}"
