name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REACT_APP_RECAPTCHA_SITEKEY: ${{ secrets.REACT_APP_RECAPTCHA_SITEKEY }}
      # Add other secrets below if needed, using the same pattern

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          npx gh-pages -d build -b gh-pages \
            -u "GitHub Actions <actions@github.com>" \
            -r "https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}"
